# Generated by Django 3.1.1 on 2020-09-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=200)),
                ('weblink', models.CharField(max_length=200)),
            ],
        ),
    ]
