# Generated by Django 3.1.1 on 2020-09-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbank2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbank',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
